[package]
name = "spellcheck"
version = "0.1.0"
edition = "2024"

[dependencies]
core-foundation = "0.10.1"
core-graphics = "0.25.0"
image = "0.25.10"
objc2 = "0.6.4"
rdev = "0.5.3"
tao = "0.37.0"
tray-icon = "0.24.2"

[package.metadata.bundle]
name = "SpellCheck"
identifier = "com.ariozdogan.spellcheck"
icon = ["assets/icons8-spellcheck-50.png"]
version = "0.1.0"
copyright = "Copyright (c) 2026 Ari Ozdogan"
category = "public.app-category.utilities"
short_description = "System-wide spell correction"
resources = ["assets/tray-icon.png", "data/frequency_dictionary.txt"]